# See https://github.com/actions/labeler

"documentation":
  - docs/**

"starter":
  - starter/**

"pkg: astropi":
  - packages/astropi/**

"devops":
  - .github/**
  - .vscode/**
  - .gitignore
  - .npmrc
  - pnpm-workspace.yaml
  - .prettierrc
