blank_issues_enabled: false
contact_links:
  - name: Any ideas or suggestions?
    url: https://github.com/goulvenclech/astropi/discussions
    about: Propose and discuss future improvements to Astropi
  - name: Support or help needed?
    url: https://github.com/goulvenclech/astropi/discussions
    about: Ask questions and get help from the community
